<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tr_ikut_ujian_model extends CI_Model
{

    public $table = 'tr_ikut_ujian';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_tes', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('list_soal', $q);
	$this->db->or_like('list_jawaban', $q);
	$this->db->or_like('jml_benar', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('nilai_bobot', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_tes', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('list_soal', $q);
	$this->db->or_like('list_jawaban', $q);
	$this->db->or_like('jml_benar', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('nilai_bobot', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tr_ikut_ujian_model.php */
/* Location: ./application/models/Tr_ikut_ujian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-01 09:22:20 */
/* http://harviacode.com */